# github repository actions 페이지에 나타날 이름
name: CI/CD using github actions & docker
# event trigger
# main 브랜치에 push가 되었을 때 실행
on:
  push:
    branches: ['test']

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # # 환경별 yml 파일 생성
      # -name: make app.yml
      # if: |
      #   contains(github.ref, 'main')
      # run: |
      #   mkdir ./src/main/resources
      #   cd ./src/main/resources
      #   touch ./app.yml
      #   echo "${{ secrets.YML}}" > ./app.yml
      # shell: sh
      #gogo
      # docker build & push to production
      - name: Docker build & push to prodction
        if: contains(github.ref, 'test')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
          docker-compose build
          docker push ${{ secrets.DOCKER_USERNAME}}/test:0.0.1

      # deploy to production
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'test')
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_KEY}}
          envs: GITHUB_SHA

          run: sudo chown -R ubuntu:ubuntu ubuntu
          script: |
            sudo su
            cd client/
            docker image prune -f
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME}}/test:0.0.1
            docker-compose up -d --build
